### ISSUE TITLE
4:3 support

### ISSUE THREAD

**Issue by basvroegop** [PlayingKarrde/switchOS#8]
Hi there! I left an issue on the gameOS repository before. It would seem like this theme does run quite nicely on the Retroid Pocket 2, which uses Android 6.

There's one quirk though: it seems like the theme is designed to work on 16:9 screens, whereas this handheld uses a 4:3 display. This means a part of the bottom screen is cut off and shows empty nothingness.

Is this something that would be easily fixable, or does it go deeper than I'm assuming right now? Thanks!

**Comment by PlayingKarrde** [comment]
Can you post a screenshot/photo? The theme should fit any aspect ratio as it was designed to be fully responsive.

**Comment by PlayingKarrde** [comment]
Fixed with 6abedaf4370632e44d7bb283cb81b3ffce293ce5
